#!/usr/bin/env ruby
# frozen_string_literal: true

lib_path = File.expand_path('../lib', __dir__)
$:.unshift(lib_path) if !$:.include?(lib_path)
require 'npm_3pp_lister/cli'

Signal.trap('INT') do
  warn("\n#{caller.join("\n")}: interrupted")
  exit(1)
end

begin
  Npm3ppLister::CLI.start
rescue Npm3ppLister::CLI::Error => err
  puts "ERROR: #{err.message}"
  exit 1
end
